### PR TITLE
Update at new API

### PR DESCRIPTION
**Pull request by AndreaGreco**
ISR API changed, upgrade

### CODE REVIEW

**Review by vlad-ivanov-name — APPROVED** [review]

**Comment by vlad-ivanov-name** [comment]
Thank you!

**Comment by AndreaGreco** [comment]
Something broken in rtos-thread

Il 09 nov 2017 08:25, "Vlad Ivanov" <notifications@github.com> ha scritto:

**Comment by vlad-ivanov-name** [comment]
I think it's GDB that's broken, it crashes while resolving stack trace often

**Comment by AndreaGreco** [comment]
It does not compile,
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x24):
undefined reference to `pxReadyTasksLists'
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x28):
undefined reference to `pxReadyTasksLists'
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x2c):
undefined reference to `pxDelayedTaskList'
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x30):
undefined reference to `pxOverflowDelayedTaskList'
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x34):
undefined reference to `xTasksWaitingTermination'
../../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x38):
undefined reference to `xSuspendedTaskList'

There a linker error,
pxReadyTasksLists',
pxDelayedTaskList',
pxOverflowDelayedTaskList',
xSuspendedTaskList,



2017-11-09 8:30 GMT+01:00 Vlad Ivanov <notifications@github.com>:

**Comment by vlad-ivanov-name** [comment]
See README:

> 
> When thread support is enabled, you need to add the following definitions to CFLAGS of your project before compiling FreeRTOS libs:
> 
> `CFLAGS+=-DportREMOVE_STATIC_QUALIFIER -DINCLUDE_pcTaskGetTaskName=1`
> 
> Run make clean after switching the state of this flag.

**Pull request merged**
